### PR TITLE
Update to RC-29

### LINKED ISSUE #17: Air quality meter and thermometer throw errors when placed
## Description (REQUIRED)

I tried placing a thermometer and an air quality meter and they disappeared in 1 or 2 seconds, and threw errors into the console

## Steps to reproduce the Issue (REQUIRED)

place either machine
2 seconds later they are gone

## Expected behavior (REQUIRED)

to not disappear

## Server Log

https://pastebin.com/ga4unCPu

## /error-reports/ Folder

https://pastebin.com/6L6Lx0tB

## Environment (REQUIRED)

 - Server Software (Spigot/Paper):paper 552
 - Minecraft Version: 1.16.5
 - Slimefun Version:867
 - CS-CoreLib Version:removed

### LINKED ISSUE #19: Error on startup
```
[04:07:59] [Server thread/INFO]: [GlobalWarming] Enabling GlobalWarming vDEV - 9 (git d21d264b)
[04:07:59] [Server thread/ERROR]: Error occurred while enabling GlobalWarming vDEV - 9 (git d21d264b) (Is it up to date?)
java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: me/mrCookieSlime/Slimefun/Objects/SlimefunItem/UnregisterReason
	at me.poma123.globalwarming.items.machines.TemperatureMeter.<init>(TemperatureMeter.java:29) ~[?:?]
	at me.poma123.globalwarming.GlobalWarmingPlugin$1.<init>(GlobalWarmingPlugin.java:102) ~[?:?]
	at me.poma123.globalwarming.GlobalWarmingPlugin.registerItems(GlobalWarmingPlugin.java:98) ~[?:?]
	at me.poma123.globalwarming.GlobalWarmingPlugin.onEnable(GlobalWarmingPlugin.java:85) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Purpur-1048]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Purpur-1048]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Purpur-1048]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Purpur-1048]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Purpur-1048]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:582) ~[patched_1.16.5.jar:git-Purpur-1048]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:292) ~[patched_1.16.5.jar:git-Purpur-1048]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1061) ~[patched_1.16.5.jar:git-Purpur-1048]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Purpur-1048]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_281]
Caused by: java.lang.NoClassDefFoundError: me/mrCookieSlime/Slimefun/Objects/SlimefunItem/UnregisterReason
	... 14 more
Caused by: java.lang.ClassNotFoundException: me.mrCookieSlime.Slimefun.Objects.SlimefunItem.UnregisterReason
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_281]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:183) ~[patched_1.16.5.jar:git-Purpur-1048]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[patched_1.16.5.jar:git-Purpur-1048]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_281]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_281]
	... 14 more
[04:07:59] [Server thread/INFO]: [GlobalWarming] Disabling GlobalWarming vDEV - 9 (git d21d264b)
```

### LINKED ISSUE #21: Incompatible with new version of SlimeFun
## Description (REQUIRED)

SF now remove SimpleHologram and registerBlockHandler should be changed to itemHandler these day

## Steps to reproduce the Issue (REQUIRED)

Use this plugin with the latest version of SF

## Expected behavior (REQUIRED)

Make it compatible with new version by using new api

## Server Log

```
[17:16:44 INFO]: [GlobalWarming] Enabling GlobalWarming vDEV - 9 (git d21d264b)
[17:16:44 ERROR]: Error occurred while enabling GlobalWarming vDEV - 9 (git d21d264b) (Is it up to date?)
java.lang.NoClassDefFoundError: me/mrCookieSlime/Slimefun/Objects/SlimefunBlockHandler
        at me.poma123.globalwarming.items.machines.TemperatureMeter.<init>(TemperatureMeter.java:29) ~[?:?]
        at me.poma123.globalwarming.GlobalWarmingPlugin$1.<init>(GlobalWarmingPlugin.java:102) ~[?:?]
        at me.poma123.globalwarming.GlobalWarmingPlugin.registerItems(GlobalWarmingPlugin.java:98) ~[?:?]
        at me.poma123.globalwarming.GlobalWarmingPlugin.onEnable(GlobalWarmingPlugin.java:85) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-640]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Paper-640]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Paper-640]
        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:366) ~[?:?]
        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:318) ~[?:?]
        at com.rylinaux.plugman.util.PluginUtil.reload(PluginUtil.java:380) ~[?:?]
        at com.rylinaux.plugman.command.ReloadCommand.execute(ReloadCommand.java:122) ~[?:?]
        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Paper-640]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Paper-640]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:810) ~[patched_1.16.5.jar:git-Paper-640]
        at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2171) ~[patched_1.16.5.jar:git-Paper-640]
        at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1986) ~[patched_1.16.5.jar:git-Paper-640]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1939) ~[patched_1.16.5.jar:git-Paper-640]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:50) ~[patched_1.16.5.jar:git-Paper-640]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:8) ~[patched_1.16.5.jar:git-Paper-640]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-640]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-640]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-640]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-640]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-640]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1262) ~[patched_1.16.5.jar:git-Paper-640]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1255) ~[patched_1.16.5.jar:git-Paper-640]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-640]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1216) ~[patched_1.16.5.jar:git-Paper-640]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130) ~[patched_1.16.5.jar:git-Paper-640]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-640]
        at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.lang.ClassNotFoundException: me.mrCookieSlime.Slimefun.Objects.SlimefunBlockHandler
        at java.net.URLClassLoader.findClass(URLClassLoader.java:435) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:182) ~[patched_1.16.5.jar:git-Paper-640]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[patched_1.16.5.jar:git-Paper-640]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
        ... 32 more
```

## Environment (REQUIRED)

 - Server Software (Spigot/Paper):
 - Minecraft Version: \
 - Slimefun Version: any version after they changed api
 - CS-CoreLib Version: \

### LINKED ISSUE #22: Fails to enable.
## Description (REQUIRED)

Plugin fails to load.

## Steps to reproduce the Issue (REQUIRED)

Start a server with Slimefun and this addon.

## Expected behavior (REQUIRED)

The plugin loading.

## Server Log

https://pastebin.com/RcvHSqkb

## /error-reports/ Folder

N/A

## Environment (REQUIRED)

At the time of creating this issue, I WAS using the latest version of Slimefun and all addons in these screenshots, but whoever answers this by then, these screenshots are basically pointless. Blame yourself for answering so late.

 - Server Software (Spigot/Paper): See 2nd screenshot.

### PR DESCRIPTION
**Pull request by ybw0014**
## Description

Update to RC-29

## Related Issues

Resolves #17 
Resolves #19 
Resolves #21 
Resolves #22 

## Checklist

- [x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [x] I followed the existing code standards and didn't mess up the formatting.
- [x] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values

### CODE REVIEW

**Comment by ybw0014** [comment]
Hi, poma. It looks like you appear in Github to approve workflow runs. 
Would you like to keep maintain this addon alive? If not, I can do this in my fork.

**Review by poma123 — CHANGES_REQUESTED** [review]
Hi, thank you for the time and effort you put into this PR. I have been extremely busy lately, and it will probably stay the same. You can always PR changes, which I will check if I have a little time. Unfortunately, I don't have the opportunity to test it out ingame due to the lack of time, so it would be much appreciated if you test your changes thoroughly.

I'm pretty much approving this, but please don't mess up the import orders, they should be ordered consistently as seen in the original files.

**Comment by ybw0014** [comment]
> I'm pretty much approving this, but please don't mess up the import orders, they should be ordered consistently as seen in the original files.

Just reformatted the imports

**Comment by ybw0014** [comment]
I posted my revised version in addon community discord, and boomer said everything works fine.

**Comment by ybw0014** [comment]
Hopefully this workflow runs well.

**Review by poma123 — APPROVED** [review]

**Pull request merged**
